### ISSUE TITLE
Got Scammed

### ISSUE THREAD

**Issue by priyankaj1910** [0xProject/swap-demo-tutorial#6]
I executed code from part 9 and 3 hours after, a fraud transaction was conducted in my wallet. Someone transferred all my token amount to this wallet 0x972506269ab19fcd560aff672d37985d5ae56858. This wallet is fraud one

**Comment by Stargazerr1** [comment]
Same thing happened to me but thanks to Blackhathacker111 who helped me get recovered my lost funds,message him on telegram his telegram username is https://t.me/Blackhathacker110
